### ISSUE TITLE
Does this require DBus?

### ISSUE THREAD

**Issue by probonopd** [ehopperdietzel/Heaven#1]
Hello, I've been working on supporting global menus in [helloSystem](https://hellosystem.github.io/).

Along the way I have documented the various bits and pieces that are apparently needed to make global menus work for Qt and Gtk applications, as well as for Electron based applications and for Firefox and Thunderbird:
https://hellosystem.github.io/docs/developer/menu.html

* Is your solution cleaner?
* Does it need DBus?
* Can it support Gtk applications?

**Comment by ehopperdietzel** [comment]
Hello, I found 'helloSystem' a while ago and it's documentation really helped me to understand how global menus work on Linux, so thanks a lot.

- Is my solution cleaner?

That's subjective, the C API is quite simple, but I still want to make some deep changes so I wouldn't recommend using it right now. It handles the IPC mechanism, errors and has a separate API for clients applications, global menu bar and compositors.
The main difference with DBusMenu is that it does not rely on X11 Windows IDs and therefore it also works on Wayland. The way it operates is as follows. Applications send their menus to the global menu bar process using the client API and the compositor (X11 or Wayland) sends the PID of the current active client (using its own policy) to the global menu bar with the compositor API so that the menu bar process know which menu it should display. If a client application creates multiple menu bars, e.g one for each of its windows, it can tell the global menu bar process which one to display when they receive keyboard focus or are activated (for example with the XDG Shell protocol in Wayland). 

- Does it need DBus?

Currently it uses Unix Domain Sockets, but I want to add support for DBus. The idea is that it first try to use DBus if available in the system, and then use UDS if not. The API in both cases would remain the same, and processes should not try to use the DBus interface directly without the library, because it is very restrictive and any bad behaved client is automatically disconnected.

- Can it support Gtk applications?

It's a C API, so it can be used in any application. But automatic support for GTK ? No. Since version 4 I am afraid GTK dropped support for external plugins so there is nothing we can do about it. But Qt still let us "inject" plugins on any app at runtime, in this case with a "Qt Platform Theme Plugin". I made one for this library [QtCuarzo](https://github.com/CuarzoSoftware/QtCuarzo).

I am in the last semester of my career and working on my thesis so I don't have much time to work in this project right now, but I could tell you when I finish it if you are interested.

**Comment by probonopd** [comment]
Thanks for your answers @ehopperdietzel, makes sense to me. I was considering to drop DBus in helloSystem while still having global menus. Maybe your solution can be used for that one day. Keep it up!

**Comment by ehopperdietzel** [comment]
> Thanks for your answers @ehopperdietzel, makes sense to me. I was considering to drop DBus in helloSystem while still having global menus. Maybe your solution can be used for that one day. Keep it up!

I know DBus is quite a nightmare, but It's architecture is actually good, it prevent us from creating a lot of pipes to comunicate processes which of course slow down the system, so I would not recommend dropping it.

Greetings!
